### ISSUE TITLE
Get dlls for use page compilations from cache storage 

### ISSUE THREAD

**Issue by KristianMariyanov** [BlazorRepl/BlazorRepl#103] opened 2021-02-18 13:40 UTC
Currently, we are creating an HTTP request for each of the dll. We can get them from the cache storage.

It will be great if we could use unmarshaled js calls

**Comment by vladislav-karamfilov** [comment] 2021-02-18 14:24
This is a duplicate of https://github.com/BlazorRepl/BlazorRepl/issues/21

**Closed by vladislav-karamfilov** 2021-02-18 14:24 UTC
Labels: enhancement, execution
